media:
  input: assets/images
  output: /assets/images
  categories:
    - uploads

content:
  - name: settings
    label: Global Settings
    type: file
    path: _data/settings.yml
    fields:
      - name: hero_title
        label: Hero Title
        type: string
      - name: hero_subtitle
        label: Hero Subtitle
        type: text
      - name: email
        label: Email Address
        type: string
      - name: phone
        label: Phone Number
        type: string

  - name: services
    label: Services
    type: list
    path: _data/services.yml
    fields:
      - name: title
        label: Service Name
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: icon
        label: Icon Name (e.g., user, leaf)
        type: string

  - name: testimonials
    label: Testimonials
    type: list
    path: _data/testimonials.yml
    fields:
      - name: author
        label: Client Name
        type: string
      - name: quote
        label: Testimonial
        type: text
